// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hncbaejeklqtaweyabfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuY2JhZWpla2xxdGF3ZXlhYmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTA2NzYsImV4cCI6MjA2NDc4NjY3Nn0.aP7n1Un-HbOqJsUsUWcIGfIDmtK5a4fuWWIyTOC0qkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);